import Header from "./Header";
import Head from "next/head";
import { ReactNode, useEffect, useState } from "react";
import ProjectSidebar from "../Sidebar/ProjectSidebar";
import { useRouter } from "next/router";
import WidgetSidebar from "../Sidebar/WidgetSidebar";

export interface Props {
	children?: ReactNode;
	title: string;
}

export const Layout = ({ title, children }: Props) => {
	const [state, setState] = useState(true);
	const router = useRouter();

	useEffect(() => {
		if (router.asPath === "/dashboard") setState(false);
	}, [router]);

	return (
		<div className=''>
			<Head>
				<title>{title}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='flex relative'>
				<ProjectSidebar />
				<div className='relative flex w-full'>
					{state && <div className='w-[260px] min-w-[260px] h-screen'> </div>}
					{state && <WidgetSidebar />}
					<div className='w-full '>
						<Header />
						{children}
					</div>
				</div>
			</div>
		</div>
	);
};

export default Layout;

Layout.auth = true;
