import Header from "./Header";
import Head from "next/head";
import { ReactNode } from "react";

export interface Props {
  children?: ReactNode;
  title: string;
}

export const Layout = ({ title, children }: Props) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
    </div>
  );
};

export default Layout;
